/* Run with Node: node tests/core.test.js. No packages required. */
if(typeof require==='function'){require('../products.js');require('../core.js');}
(function(root){
  'use strict';
  const C=root.DogCore,results=[];
  function test(name,fn){fn();results.push(name);}
  function equal(a,b){if(a!==b)throw Error(`${a} !== ${b}`);}
  function near(a,b,tolerance=0.01){if(Math.abs(a-b)>tolerance)throw Error(`${a} is not close to ${b}`);}
  function rejects(fn){let caught=false;try{fn();}catch{caught=true;}if(!caught)throw Error('Expected rejection');}
  test('Стандартный план и все покупки',()=>{const s=C.defaults(),v=C.calculate(s);equal(v.total,8400);near(v.batches,12.72727);near(v.rows[0].grams,2863.636);near(v.rows[1].grams,2354.545);near(v.rows[1].dry,941.818);equal(v.rows[2].grams,1400);equal(v.rows[3].grams,700);equal(v.rows[4].grams,700);near(v.rows[5].grams,343.636);near(v.rows[5].spoons,25.4545);near(v.energy,967.63);near(v.density,146.6106);near(v.dogCalories[0],1466.106);near(v.dogCalories[1],293.221);});
  test('Изюбрь: одна позиция, оригинал не меняется',()=>{const s=C.defaults(),change=C.replacement(s,0,'deer');equal(change.r.items.length,6);equal(change.r.items[0].grams,225);equal(C.original.items[0].product,'beef');const v=C.calculate(s,change.r);near(v.energy,816.88);near(v.dogCalories[0],1237.697);});
  test('Сохранение калорий и предупреждение о белке',()=>{const v=C.replacement(C.defaults(),0,'turkey','calories');near(v.grams,365.869565);equal(v.protein,true);equal(C.original.items[0].grams,225);});
  test('Все масла: калории ложки вычисляются одной формулой',()=>{const s=C.defaults();for(const [id,kcal,grams,spoon] of [['olive',899,13.5,121.365],['coconut',892,13,115.96],['flax',884,13.5,119.34]]){const p=C.product(s,id);equal(p.kcal,kcal);equal(p.spoonGrams,grams);near(C.spoonCalories(p),spoon,1e-9);const r=C.clone(C.original);r.items[5]={product:id,grams:grams*2};const other=r.items.slice(0,5).reduce((n,i)=>n+i.grams*C.kcal(C.product(s,i.product))/100,0);near(C.calculate(s,r).energy-other,spoon*2,1e-9);}});
  test('Калории продукта сохранены, калории собак показаны до и после',()=>{const s=C.defaults(),before=C.calculate(s),r=C.replacement(s,0,'turkey','calories').r,after=C.calculate(s,r);near(before.energy,after.energy,1e-9);equal(after.y,800);const rows=C.portionImpact(s.dogs,before.density,after.density);near(rows[0].before,1466.106);near(rows[0].after,1209.5375);near(rows[1].after,241.9075);near(rows[0].percent,-17.5);near(rows[1].percent,-17.5);equal(s.dogs[0].portion,1000);equal(s.dogs[1].portion,200);s.dogs.forEach((d,i)=>d.portion=rows[i].portion);const adjusted=C.calculate(s,r);near(adjusted.dogCalories[0],before.dogCalories[0],1e-9);near(adjusted.dogCalories[1],before.dogCalories[1],1e-9);near(s.dogs[0].portion,1212.121212);near(s.dogs[1].portion,242.424242);});
  test('Сравнение учитывает взвешенный выход и обе порции отдельно',()=>{const s=C.defaults();s.dogs[1].portion=180;s.yields.original={value:900,date:'2026-10-02',fingerprint:C.fingerprint(C.original)};const before=C.calculate(s),r=C.replacement(s,0,'deer').r,after=C.calculate(s,r),rows=C.portionImpact(s.dogs,before.density,after.density);near(rows[0].before,1000*before.energy/900);near(rows[1].before,180*before.energy/900);near(rows[1].portion,180*before.density/after.density);});
  test('История замены совместима с экспортом v2',()=>{const s=C.defaults(),r=C.replacement(s,0,'turkey','calories').r;s.recipes=[{...r,id:'recipe-impact'}];s.selected='recipe-impact';s.replacementImpact={recipeId:s.selected,fingerprint:C.fingerprint(r),beforeDensity:C.calculate(C.defaults()).density,beforePortions:[1000,200]};equal(JSON.stringify(C.validate(s)),JSON.stringify(s));s.replacementImpact.beforeDensity=0;rejects(()=>C.validate(s));});
  test('Напоминание через 14 дней, отсрочка и отключение',()=>{const start=1000000,period=14*86400000,meta={startedAt:start,backupEnabled:true};equal(C.backupDue(meta,start),false);equal(C.backupDue(meta,start+period-1),false);equal(C.backupDue(meta,start+period),true);meta.lastBackupReminder=start+period;equal(C.backupDue(meta,start+period+1),false);equal(C.backupDue(meta,start+period*2),true);meta.backupEnabled=false;equal(C.backupDue(meta,start+period*10),false);});
  test('Калибровка крупы',()=>{const s=C.defaults();equal(185/C.product(s,'buckwheat').coefficient,74);s.grainSettings.buckwheat={coefficient:2.7,kcal:330};equal(Math.round(185/C.product(s,'buckwheat').coefficient),69);near(C.calculate(s).rows[1].dry,2354.54545/2.7);});
  test('Другие дни и независимые порции',()=>{const s=C.defaults();s.dogs[0].portion=1100;s.dogs[1].portion=180;s.days=10;equal(C.calculate(s).total,12800);s.dogs[1].portion=s.dogs[1].standard;equal(s.dogs[0].portion,1100);s.dogs[0].portion=1000*0.9;equal(s.dogs[0].portion,900);equal(s.dogs[1].portion,200);});
  test('Взвешивание, изменение состава и новая оценка',()=>{const s=C.defaults();s.yields.original={value:800,date:'2026-10-02',fingerprint:C.fingerprint(C.original)};const v=C.calculate(s);equal(v.batches,10.5);equal(v.rows[0].grams,2362.5);const r=C.clone(C.original);r.items[0].grams=300;equal(C.yieldInfo(s,r).changed,true);equal(C.yieldInfo(s,r).value,730);delete s.yields.original;equal(C.calculate(s).y,660);});
  test('Мини-партия не меняет общий рецепт',()=>{const s=C.defaults(),before=JSON.stringify(s),r=C.gentle(),v=C.calculate(s,r,200*3);equal(v.total,600);equal(JSON.stringify(s),before);equal(v.rows[1].p.id,'rice');});
  test('Ориентиры калорий используют правильный вес',()=>{const d={weight:30,targetWeight:25,neutered:true,goal:'maintain'};near(C.target(d).low,70*30**0.75*1.6);d.goal='lose';near(C.target(d).low,70*25**0.75);d.goal='gain';near(C.target(d).high,70*25**0.75*1.4);});
  test('JSON сохраняет полную точность и допустимые данные',()=>{const s=C.defaults();s.recipes=[{id:'recipe-test',name:'Моя копия',items:C.replacement(s,0,'turkey','calories').r.items}];s.selected='recipe-test';equal(JSON.stringify(C.validate(JSON.parse(JSON.stringify(s)))),JSON.stringify(s));});
  test('Некорректный JSON отклоняется без разрушения состояния',()=>{for(const mutate of [s=>s.days=0,s=>s.days=61,s=>s.days=1.2,s=>s.dogs[0].portion=-1,s=>s.dogs[0].portion=null,s=>s.dogs[0].weight=-2,s=>s.selected='missing',s=>s.recipes.push({id:'recipe-a',name:'Test',items:[{product:'unknown',grams:10}]}),s=>s.grainSettings.buckwheat={coefficient:0,kcal:330},s=>s.customProducts.push({id:'custom-a',name:'Луковый порошок',category:'vegetable',kcal:40,note:''})]){const s=C.defaults();mutate(s);rejects(()=>C.validate(s));}rejects(()=>C.validate({}));});
  test('Стоп-лист и безопасные названия',()=>{for(const name of ['чеснок','Луковый порошок','Свинина','Свиной фарш','Грибы','Шоколад','изюм','Ксилитол','Рыбий жир','Подсолнечное масло','Варёные кости'])equal(C.blocked(name),true);for(const name of ['Изюбрь','Говядина','Брокколи','Тыква','Индейка'])equal(C.blocked(name),false);});
  root.DogTestResults=results;
  if(typeof console!=='undefined'){results.forEach(name=>console.log('PASS '+name));console.log('Проверок пройдено: '+results.length);}
})(globalThis);
