"""Generate one APP_VERSION when app contents change; no dependencies."""
import argparse
import hashlib
import re
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
APP_FILES = ['index.html', 'style.css', 'products.js', 'core.js', 'app.js',
             'sw.js', 'manifest.webmanifest', 'icons/icon-192.png', 'icons/icon-512.png']
PUBLIC_FILES = APP_FILES + ['version.js', '.nojekyll', '.gitignore', 'README.md',
                            'tests/core.test.js', 'tests/sw.test.js',
                            'tools/build.py', 'tools/prepare_pages.py',
                            'tools/make_icons.py', 'tools/make_pages_qr.py']

def build(check=False):
    digest = hashlib.sha256()
    for name in APP_FILES:
        digest.update(name.encode('utf-8') + b'\0' + (ROOT / name).read_bytes())
    fingerprint = digest.hexdigest()[:16]
    dest = ROOT / 'version.js'
    current = dest.read_text('utf-8') if dest.exists() else ''
    if not re.search(r"-" + fingerprint + r"'", current):
        if check:
            raise SystemExit('Version is stale. Run: python tools/build.py')
        version = datetime.now(timezone.utc).strftime('%Y%m%dT%H%M%SZ') + '-' + fingerprint
        dest.write_text("/* Generated by tools/build.py. */\nconst APP_VERSION = '" + version + "';\n", 'utf-8')
    print(dest.read_text('utf-8').strip())

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--check', action='store_true')
    build(parser.parse_args().check)
